name: Deploy to Staging Site

on:
  push:
    branches:
      - React

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Retrieve Maps and Music
      run: cp ${{ secrets.ASSETFILEURL }} .
    - name: Extract Maps and Music
      run: tar -xvf PerfectEye.tar -C public/assets
    - name: Create site
      run: npm publish
