name: Deploy to Staging Site

on:
  push:
    branches:
      - React
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull down code base
      uses: actions/checkout@v3
    - name: Stop old Docker Container
      run: docker stop PerfectEyeDev || true
    - name: Remove old Docker Container
      run: docker rm PerfectEyeDev || true
    - name: Remove old Docker Image
      run: docker rmi PerfectEyeDev:latest || true
    - name: Retrieve Maps and Music
      run: cp ${{ secrets.ASSETFILEURL }} .
    - name: Extract Maps and Music
      run: tar -xvf PerfectEye.tar -C public/assets
    - name: Install dependancies
      run: npm ci
    - name: Run Npm Build
      run: CI='' npm run build
    - name: Build the new Docker image
      run: docker build . --file Dockerfile --tag PerfectEyeDev:latest
    - name: Start the new image
      run: docker run -d --name PerfectEyeDev -p 8080:3000 --restart always PerfectEyeDev:latest  
