name: Deploy to Production Site

on:
  push:
    branches:
      - Main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull down code base
      uses: actions/checkout@v3
    #- name: Retrieve Maps and Music
    #  run: cp ${{ secrets.ASSETFILEURL }} .
    #- name: Install dependancies
    #  run: npm ci
    #- name: Run Npm Build
    #  run: CI='' npm run build
    - name: Upload files to Production
      env:
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        FTP_ADDRESS: ${{ secrets.SERVER }}
        FTP_PORT: ${{ secrets.PORT}}
      run: |
        sudo apt-get install -y expect  # Install expect to handle password automation

        expect << EOF
        spawn sftp -P $SFTP_PORT $SFTP_USERNAME@$SFTP_SERVER
        expect "password:"
        send "$SFTP_PASSWORD\r"
        expect "sftp>"
        send "cd PerfectEye"  # Change to the correct remote directory
        send "put -r ./dist\r"     # Upload your local directory (e.g., dist)
        expect "sftp>"
        send "bye\r"
        EOF
