name: Deploy to Production Site

on:
  push:
    branches:
      - Main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull down code base
      uses: actions/checkout@v3
    #- name: Retrieve Maps and Music
    #  run: cp ${{ secrets.ASSETFILEURL }} .
    #- name: Install dependancies
    #  run: npm ci
    #- name: Run Npm Build
    #  run: CI='' npm run build
    - name: Upload files to Production
      env:
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        FTP_ADDRESS: ${{ secrets.SERVER }}
        FTP_PORT: ${{ secrets.PORT}}
      run: |
        expect << EOF
        spawn sftp -o StrictHostKeyChecking=no -P $FTP_PORT $FTP_USERNAME@$FTP_ADDRESS
        expect "password:"
        send "$FTP_PASSWORD\r"
        expect "sftp>"
        send "cd PerfectEye\r"
        expect "sftp>"
        send "put -r ./dist/*\r"
        expect "sftp>"
        send "bye\r"
        expect eof
        EOF
